### ISSUE TITLE
[FEATURE REQUEST] add non permant live streams to homescreen

### ISSUE THREAD

**Issue by bungh0l10** [mzedd/LMS-ARD-Audiothek-Plugin#21]
Hi @mzedd,

ARD introduced a very cool thing, which I personally would welcome getting introduced into your plugin as well.
App and web version of ARD Audiothek introduce you to non permanent livestreams (eg. [1,2] Bundesliga) at the home screen a couple of hours before stream gets online (Sophora fast access). The app itself highlights current live streams for each channel now as well. While I'm aware that permanent live streams are easily accessible, which works like a charm already, I'd like to request making non permanent live streams as mentioned before available to your plugins home screen as well. 
That would give a stellar user experience and alligns having the app UX.

cheers

**Comment by mzedd** [comment]
Hi @bungh0l10,
i implemented a change into my local development branch, which should include live streams into the home screen. But i haven't got a chance to test these changes, since the next Bundesliga live streams will be on 12.01. I will push the changes if the test is successful. Unfortunately i haven't found a better way to test this.

**Comment by bungh0l10** [comment]
Hi @mzedd,
great news! And you're right, it was definitely not the best time opening the FR😆. Sorry for that.

Please let me know if I can support in any way.

Cheers

**Comment by bungh0l10** [comment]
Hi @mzedd ,
I applied your commit [8c4cad7](https://github.com/mzedd/LMS-ARD-Audiothek-Plugin/commit/8c4cad715548097618b49435fb182f5b3c48ca31) from your dev branch to my local install and all "live appearances" are available/accessible within "Entdecken" and it's headers/folders - very nice :).

Are you planning to put another section (maybe only a temporary one IF such streams are available) to the homescreen that it looks like :

- Entdecken
- Sender
- Rubriken
- Live

where "Live" contains for example (as of now):
- Live: Bundesliga am Samstag (header/folder) -> items...
- Live: 2. Bundesliga am Samsatg (header/folder) -> items...
- Deutschland - Österreich | Handball-EM (item)

Or do you prefer listing all live items on the homescreen directly?

thanks and cheers

**Comment by mzedd** [comment]
Hi @bungh0l10,
currently i would prefer to not add an extra section for live events, but rather align the app with the current AT web structure as you suggested in #23 even more. But i haven't decided on a structure yet, since the LMS API doesn't given you a great freedom on how to display stuff.
If you want fast access to the livestreams temporarily you can just add them to your LMS favorites.

**Comment by bungh0l10** [comment]
Hey @mzedd , 
no worries I'm more then happy having/ using the provided shortcut. Thinking about twice also makes it pretty much clear no extra (temp) section is needed 😄
